version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: my-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/simple-auth
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads  # Add this line to persist uploaded files

volumes:
  mongo-data:
